voxpupuli/puppet-postfix

manifests/params.pp

Removing lucid from mailx_package selector

---

manifests/service.pp

Reverts camptocamp/puppet-postfix#67

Revert "Update service.pp"

---

manifests/hash.pp

fix validation for source and content vars

---

README.md

since we already link to the style-guide in the how-to-contribute section, let's stick to it in our documentation ;)

consistent formating of the documentation

---

README.md
manifests/conffile.pp
spec/defines/postfix_conffile_spec.rb
templates/conffile.erb

With it you can create postfix config files. It is a file, but it also reload postfix.

Add conffile define

---

manifests/hash.pp

Fix hash.pp doc

---

manifests/init.pp
manifests/service.pp

Using this two parameters is possible to manage the service

Added parameters postfix::service_ensure and postfix::service_enabled

---

templates/master.cf.redhat.erb

Add retry to redhat master.cf

---

manifests/params.pp
metadata.json
spec/classes/postfix_spec.rb

Update cases to include RedHat 8 with appropriate values

Add RedHat 8 support

---

manifests/transport.pp
spec/defines/postfix_transport_spec.rb

Transport: allow [host]:port smtp syntax

---

metadata.json

Drop Debian 7/8/9; Add 10/11; Drop Ubuntu 14/16; Add 20.04

---

manifests/map.pp

puppet-lint: fix top_scope_facts warnings

---

README.md
manifests/init.pp

Update documentation with missing parameter manage_mailname to resolve issue #186

Add manage_mailname parameter  to README (#186)

---

metadata.json

Update dependency on puppet/alternatives to its next major version
Fixes #324

increase dependency of puppet/alternatives to next major version

---

.github/SECURITY.md
.gitignore
CHANGELOG.md
Gemfile
REFERENCE.md
Rakefile
metadata.json

As noted in #346, the documentation of the latest version of the module on the forge is a bit misleading and quite a number of fixes have been integrated since the last release in May last year.
We also have #256 which introduce a breaking change, so I propose to do a release without it for now, and merge that PR when it is done.
This PR also include:
* #348

Release 3.1.0

---

metadata.json

puppet/alternatives: Allow 5.x

---

CHANGELOG.md
metadata.json

Release 4.2.1

---

REFERENCE.md
manifests/conffile.pp
manifests/hash.pp
manifests/map.pp

use Stdlib::Filemode datatype for mode parameters

---

REFERENCE.md
manifests/canonical.pp
spec/defines/postfix_canonical_spec.rb

postfix:canonical: Add unit tests

---

CHANGELOG.md
metadata.json

Release 4.3.0

---

metadata.json

Add Alma/Rocky/Oracle support

---

CHANGELOG.md
metadata.json

Release 4.4.0

---

REFERENCE.md
manifests/init.pp

Allow mailaliases to be managed via hiera
n/a

Allow `mailaliases` to be managed via hiera

---

metadata.json

Bump puppet-alternatives version constraint to include 7.0 in puppet-postfix
N/A

bump puppet-alternatives version constraint

---

metadata.json

drop support for freebsd 12 -- EOL

---

metadata.json

drop support for fedora 33 & 34 -- EOL

---

metadata.json

drop support for EL7 -- EOL

---

metadata.json

drop support for debian 10 -- EOL

---

metadata.json

drop support for centos 8 -- EOL

---

metadata.json

drop support for ubuntu 18.04 -- EOL

---

CHANGELOG.md
metadata.json

Version release for puppet-alternatives version constraint to include 7.0
N/A

Release 4.5.0
