voxpupuli/puppet-postfix

manifests/params.pp, manifests/service.pp, spec/classes/postfix_spec.rb
on red hat and centos 7 the postfix daemon is managed via systemd.  This changes the restart command for the service to use the systemctl command when the system is running rhel/centos 7.
=> Systemd restart support

manifests/params.pp, templates/master.cf.sles.erb
A diff between the master.cf that comes with the sles package and the changes I did:
```patch
--- sles_master.cf	2015-06-14 14:02:24.837255195 +0200
+++ templates/master.cf.sles.erb	2015-06-14 13:31:54.094174891 +0200
@@ -1,3 +1,4 @@
+# file managed by puppet
#
@@ -9,7 +10,19 @@
+<% if @master_smtp -%>
+<%= @master_smtp %>
+<% elsif @smtp_listen == 'all' -%>
smtp      inet  n       -       n       -       -       smtpd
+<% else -%>
+<%= @smtp_listen %>:smtp      inet  n       -       n       -       -       smtpd
+<% end -%>
+<% if @master_submission -%>
+<%= @master_submission %>
+<% end -%>
+<% if @master_smtps -%>
+<%= @master_smtps %>
+<% end -%>
#amavis    unix  -       -       n       -       4       smtp
@@ -57,7 +70,9 @@
proxymap  unix  -       -       n       -       - …
```
=> Add support for SLES 12 and newest openSUSE releases

manifests/files.pp, manifests/params.pp, spec/classes/postfix_spec.rb
On RHEL 6&7, the SELinux type of /etc/aliases is etc_aliases_t.
The module set a postfix_etc_t. It works too, but, as discussed, it's better to keep that RedHat provides.
I keep a case with "/6|7/", just to update to the right type, without waiting for the next types restore. It's not required for a new system, and I don't mind if we just removed this case.
=> Use RHEL SELinux type for /etc/aliases

manifests/init.pp, manifests/packages.pp
so that we can be able to define specific package versions (or latest)
=> add ensure class arguments for the packages

manifests/files.pp, manifests/init.pp, spec/classes/postfix_spec.rb
Add manage_root_alias parameter to disable management of root's mailalias resource
I use a module that specifically manages the root user, and part of that's modules responsibility is root's mailalias.
=> Add manage_root_alias parameter

manifests/hash.pp, spec/defines/postfix_hash_spec.rb
Seems /etc/postfix/virtual and /etc/postfix/transport on a fresh install don't trigger a refresh of the postmap exec, so the File resource for the db file ends up creating a 0 byte file.  
May address #130
=> Fix virtual.db and transport.db creation

README.md, manifests/init.pp, manifests/packages.pp, spec/classes/postfix_spec.rb
This supercedes #141.
I wonder if $ensure_mailx and $manage_mailx are a little redundant, though obviously ensure absent is slightly different from not managing it at all.
I did add a unit test, but got some Hiera errors when trying to run the spec tests locally (would be great if someone could fix whatever is causing the Travis CI tests to fail, as it seems to be happening for all PRs; some more docs about what is needed to run tests locally would also be helpful)
=> Add $manage_mailx boolean to control whether mailx is managed

manifests/hash.pp, manifests/map.pp, spec/defines/postfix_hash_spec.rb, spec/defines/postfix_map_spec.rb
It is similar to existing hash define, but this define can create maps
of any type, not just hash.
=> Add a map define to create postfix maps

manifests/map.pp
The postmap command needs the complete path of the database. In the exec the `$name` was used, while it needs `$path`.
=> Fix the path of the map database

manifests/hash.pp
map defines the default path by prepending '/etc/postfix/' to $name, so
this doesn't work when the name is already the absolute path. We need
to force the path passed to map.
=> Fix map calling in hash

templates/master.cf.SLES11.4.erb
The module fails on SLES 11 SP4 , as the template for this OS release is missing. The module only verifies the operatingsystem and if is SLES, it assigns the corresponding template, based on the system release.
=> master.cf template for SLES 11 SP4

manifests/files.pp, manifests/init.pp, spec/classes/postfix_spec.rb
Adds a parameter for inet_protocols with a default value of 'all' (the Postfix default.) 
The goal is to give the option of setting the appropriate value for clients where IPV6 is disabled. Postfix will not start with the default value if an IPV6 interface is not present.
=> Add inet_protocols option

manifests/params.pp
Without it module fails on Debian stretch
=> Fix package name resolution for Debian stretch

manifests/transport.pp, manifests/virtual.pp, spec/defines/postfix_hash_spec.rb, spec/defines/postfix_transport_spec.rb, spec/defines/postfix_virtual_spec.rb
Dependencies must be set only if the resources exist in the catalog.
For some weird reason, this worked in Puppet 4 (and shouldn't have).
=> Fix resource dependencies

files/lenses/postfix_virtual.aug, files/lenses/test_postfix_virtual.aug, manifests/augeas.pp
Fixes #176 
This basically syncs the internal lens with the version in upstream.
We are still on augeas 1.4.0 which doesn't have this code.
I have set the stock_version to 1.7.0 so this will be installed.
=> Update postfix::virtual augeas lens to match upstream version

README.md, manifests/files.pp, manifests/init.pp, templates/master.cf.common.erb
It is an optional array of strings containing addtional entries for the
master.cf file
=> Add master_entries parameter to postfix

.fixtures.yml, manifests/conffile.pp, manifests/files.pp, manifests/hash.pp, manifests/init.pp, manifests/map.pp, manifests/service.pp, metadata.json, spec/classes/postfix_augeas_spec.rb, spec/classes/postfix_spec.rb, spec/spec_helper_acceptance.rb
Closes: #195, #124
Alternative approach to #194 that requires the [alternatives](https://github.com/voxpupuli/puppet-alternatives) module.
Debian-based distros only allow one MTA to be installed, so installing postfix will uninstall any previously-installed MTA.
Redhat-based distros, however, allow multiple MTA's to be concurrently installed, and use the alternatives mechanism to select which of them should provide the /usr/sbin/sendmail binary.
This PR also fixes a minor spelling error in the manifests/init.pp file, and ensures that map files (which may contain sensitive passwords) are not globally readable by default.
=> Install /usr/sbin/sendmail alternative on RedHat

manifests/files.pp, manifests/service.pp
This should fix the newalias issues found in the following tickets: #192 #136
=> Moved Exec['newaliases'] to services so it could be run after service restart

manifests/files.pp
The sendmail command was recently broken: https://github.com/camptocamp/puppet-postfix/pull/199#issuecomment-361594549
This Pull-Request unbreaks the sendmail command and relax some permissions which where changed from the default to more restrictive ones.
=> Unbreak sendmail

manifests/params.pp, metadata.json
Simple changes in params.pp to support Alpine Linux (osfamily=Linux, operatingsystem=Alpine).
=> Support for Alpine Linux

manifests/map.pp
Ensure that, if a map file is removed but the associated source
file is not touched, the map file is regenerated by puppet.
Tested locally, to ensure that map files have correct permissions with the reversed order of file resource and map generation, and to ensure that map files get correct content created if removed.
=> Ensure that map files are regenerated if removed (Fix #161)

metadata.json
This will allow use with current stdlib from Puppet Forge.
=> Allow puppetlabs-stdlib < 6.0.0

manifests/files.pp, manifests/mailalias.pp
=> Add postfix::mailalias, that creates an email alias and updates the binary version of the local alias database.

manifests/init.pp, templates/master.cf.common.erb
Schleuder 2.x has been deprecated for a while. It's not maintained
anymore, has obsolete dependencies, and has been superseded by
Schleuder 3.
The new syntax is documented on
https://schleuder.org/schleuder/docs/server-admins.html#postfix
=> Schleuder: port invocation syntax to Schleuder 3.

manifests/hash.pp, manifests/map.pp
This allows `Sensitive` content to be used.  eg.
```puppet
postfix::hash { '/etc/postfix/sasl_passwd':
ensure  => present,
content => Sensitive("#Destination                Credentials\n[${relay_host}]            ${username}:${password}"),
}
```
`File` will then redact the content
```
Notice: /Stage[main]/Base::Mail/Postfix::Hash[/etc/postfix/sasl_passwd]/Postfix::Map[/etc/postfix/sasl_passwd]/File[postfix map /etc/postfix/sasl_passwd]/content: [diff redacted]
Notice: /Stage[main]/Base::Mail/Postfix::Hash[/etc/postfix/sasl_passwd]/Postfix::Map[/etc/postfix/sasl_passwd]/File[postfix map /etc/postfix/sasl_passwd]/content: changed [redacted] to [redacted]
```
=> Allow `Sensitive` postfix::hash/map content

README.md, manifests/init.pp, spec/classes/postfix_spec.rb
With configs hash user can define configuration values in hiera.
This is a simplified replacement for https://github.com/camptocamp/puppet-postfix/pull/232
=> Introduce new parameter 'config' for adding configuration using hiera

templates/master.cf.debian.erb
Fixes #252 
It looks that it is missing `retry` entry only in template of Debian family OSes. It is already present in others families.
It looks that it is missing `proxy_write` entry in RedHat and Debian OSes. 
Accordingly with [proxy_write_maps](http://www.postfix.org/postconf.5.html#proxy_write_map) it looks that it should be present also in CentOS7 at least. But to be preservative, i only added it in Debian family.
=> add retry and proxywrite for debian family OSes

README.md
Add missing inet_protocols parameter to the README.
=> Add missing inet_protocols parameter to the README.

metadata.json
Version 3.0.0 of Forge Module puppet-alternatives has been out since March of 2019. It does not appear to have breaking changes. It would be nice for the dependencies on the Postfix module to reflect the latest versions.
=> Upping version dependency on puppet-alternatives

manifests/files.pp, manifests/init.pp, manifests/service.pp, spec/acceptance/postfix_spec.rb
A short pickup from PR #238 (thx your1p!) to fix #237 to add the possibility to unmanage "/etc/aliases".
=> Add the possibility to manage (or not) aliases

manifests/files.pp, manifests/init.pp, spec/classes/postfix_spec.rb
based upon https://github.com/camptocamp/puppet-postfix/pull/91
now supports master.cf from:
- source (as before)
- content (to allow the user to use their prefered content source
- template name (to still be able to use all this modules variables easily
=> Feature/allow specify master cf content & template

manifests/transport.pp, manifests/virtual.pp
In my version of this module I had a virtual_regexp and a transport_regexp class, so I started to port those over to your module so I could submit a pull request, but I realized that the way its done here these can be handled with the regular virtual and transport classes with the right configuration. So instead of porting that unnecessary code, I just enhanced the examples in  your classes to show how you can have this functionality.
=> Add virtual and transport regexp examples

manifests/map.pp, spec/defines/postfix_map_spec.rb
Fixes an issue where if a postfix map $ensure is 'absent' the postmap exec resource causes puppet runs to fail.
Tried to get this annoying bug fixed a couple of years ago (https://github.com/camptocamp/puppet-postfix/pull/151), I see it's still sitting there. Hopefully I'll have more luck this time. Can this be merged?
=> Fixes postmap when ensure=absent

manifests/files.pp, manifests/init.pp, templates/master.cf.common.erb
We found it necessary to have more running smtp processes that feed mail through amavis -- it helps process mail faster on servers with more resources, so I've put in a new variable that will set this.  I made the default to be '2', so it does not change anything for a default installation.
Also, 'smtpd_bind_address' is not a setting in Postfix, but 'smtp_bind_address' is.
=> more than two amavis processes

manifests/transport.pp
The relationship definition for the map path in `Postfix::Transport` was
hardcoded, so that any non-standard `$file` parameter did not create an
automatic refresh of the map, even if it is defined as a
`Postfix::Hash`.
Fixed be replacing the hardcoded string with the `$file` variable, which
means no change with expected behaviour.
=> Fix hardcoded map path

data/common.yaml, data/os/FreeBSD.yaml, manifests/canonical.pp, manifests/conffile.pp, manifests/config.pp, manifests/files.pp, manifests/init.pp, manifests/ldap.pp, manifests/mailman.pp, manifests/map.pp, manifests/mta.pp, manifests/packages.pp, manifests/satellite.pp, manifests/service.pp, manifests/transport.pp, manifests/virtual.pp, metadata.json, spec/classes/postfix_spec.rb, spec/defines/postfix_config_spec.rb, spec/defines/postfix_map_spec.rb, spec/defines/postfix_transport_spec.rb, spec/defines/postfix_virtual_spec.rb, templates/master.cf.FreeBSD.erb
=> Add FreeBSD support

data/osfamily/RedHat/9.yaml, metadata.json, spec/acceptance/postfix_spec.rb
* Add CentOS 9 to metadata.yml
* Install s-nail on CentOS/RHEL 9 as mailx package does not exist.
Note on Fedora mailx is still fine as mailx or s-nail are available as alternatives for mailx command.
=> Declare CentOS 9 Support, Install s-nail on 9

README.md, manifests/init.pp, manifests/mta.pp, manifests/satellite.pp, spec/classes/postfix_mta_spec.rb
When setting up simple mail routing, it is handy to have a quick way to setup domain masquerade to convert messages for DKIM or SPF acceptance.
None
=> Add switches for simple domain masquerade

manifests/mta.pp, manifests/satellite.pp
Fixes variable typos that has been added with Pull Request #326.
This is just cosmetic since this values are also pick_default inside `postfix::mta` and does result to the same catalog on the systems even when it here results to pass `undef` to `postfix::mta`.
Note for this Change these Lines, that are not used but now will with this PR: https://github.com/voxpupuli/puppet-postfix/blob/f3978930db8055a54bf75118b11a0d5e8dcfd1d7/manifests/satellite.pp#L43-L45
None
=> Fix typos errors in postfix::satellite from PR 326

manifests/canonical.pp, manifests/hash.pp, manifests/init.pp, manifests/mailman.pp, manifests/map.pp, manifests/mta.pp, spec/defines/postfix_map_spec.rb
This PR introduces the option to overwrite the previous hardcoded lookup table type ("hash"). This is required for at least Alpine (recent versions) and SLES 15. See #335 
Fixes #335
=> Add option to select lookup table type

manifests/transport.pp, spec/defines/postfix_transport_spec.rb
This expands the testing on host/port combinations in nexthop in order to allow more options to get handled correctly.
I'm not an expert on this by any means, but I think this covers the edge cases that #311 brings up?
Fixes #311
=> Handle [host] vs [host]:port nexthop

manifests/init.pp
It is less surprising if the puppet module's default configuration matches a standard default postfix configuration.
=> init.pp: use the postfix default for mydestination

.fixtures.yml, README.md, metadata.json, spec/classes/postfix_spec.rb, spec/defines/postfix_transport_spec.rb, spec/defines/postfix_virtual_spec.rb
camptocamp/puppet-augeas depends on puppetlabs/augeas_core while itself being out of support.  This removes references to the camptocamp module and goes straight to using augeas_core.
This shouldn't introduce any new dependency that wasn't inherently already there.
#353 mentions puppet8 in the title but this module fix in the description.  Out of an abundance of caution of not stepping on someone else's issue, I'm not marking this as 'fixes'.
=> Remove camptocamp/puppet-augeas dependency

.fixtures.yml, README.md, metadata.json, spec/classes/postfix_spec.rb, spec/defines/postfix_transport_spec.rb, spec/defines/postfix_virtual_spec.rb
Reverts voxpupuli/puppet-postfix#363
reverting this because https://github.com/voxpupuli/puppet-postfix/blob/master/manifests/augeas.pp still uses it.
=> Revert "Remove camptocamp/puppet-augeas dependency"

metadata.json, spec/setup_acceptance_node.pp
=> Add Debian 12 support

lib/augeas/lenses/postfix_canonical.aug, lib/augeas/lenses/test_postfix_canonical.aug
Add support for a wider range of e-mail addresses.
From [RFC 3696](https://datatracker.ietf.org/doc/html/rfc3696) (informational only but referring to [RFC 2821](https://datatracker.ietf.org/doc/html/rfc2821) and [RFC 2822](https://datatracker.ietf.org/doc/html/rfc2822)):
```
Without quotes, local-parts may consist of any combination of
alphabetic characters, digits, or any of the special characters
! # $ % & ' * + - / = ?  ^ _ ` . { | } ~
period (".") may also appear, but may not be used to start or end the
local part, nor may two or more consecutive periods appear.  Stated
differently, any ASCII graphic (printing) character other than the
at-sign ("@"), backslash, double quote, comma, or square brackets may
appear without quoting.  If any of that list of excluded characters
are to …
```
=> Extend canonical augeas lens regex

REFERENCE.md, data/osfamily/Debian.yaml, data/osfamily/RedHat/9.yaml, manifests/init.pp, manifests/ldap.pp
Install postfix-ldap package when ldap=true on RHEL8+
Fixes #397
=> postfix-ldap required for ldap lookup type on RHEL8+

spec/classes/postfix_spec.rb
Resolves this GHA warning:
postfix on debian-11-x86_64 when specifying a custom mastercf_template does stuff
Skipped: need to write this still
=> rm duplicated spec example

templates/master.cf.redhat.erb
Update default RedHat master.cf configuration
Fixes  #416
=> update default RedHat master.cf

data/osfamily/RedHat/10.yaml
adding 10 to metadata.json would require updating testing pipelines, I think, but this will benefit early adopters
=> feat: add hiera data for RHEL10

REFERENCE.md, data/osfamily/RedHat.yaml, manifests/init.pp, manifests/service.pp
Currently, resource is created unconditionally on Redhat family, but recent fedora packages moved binary to `/usr/bin/sendmail.postfix`. This change makes it backwards compatible, but allows override the path if required.
=> feat: make mta alternative configurable

data/common.yaml, templates/master.cf.default.erb
Even if a specific OS is not supported according to `metadata.json`, Puppet should not fail with
`Class[Postfix::Params]: expects a value for parameter 'master_os_template'`
Instead it should use a Default-Template for `master.cf`.
The here provided Template is the restored Suse-Template deleted in 8cf7f1ef2f469c21ce10053a6b2a7aebc167d047.
Fixes #418
=> Set a default value for `postfix::params::master_os_template`

REFERENCE.md, manifests/init.pp, spec/classes/postfix_spec.rb
New canonicals parameter can be used for easily defining `postfix::canonical` resources as a hash in hiera data.
e.g.
```yaml
postfix::canonicals:
root:
ensure: present
destination: "root_%{facts.networking.hostname}@example.ch"
file: 'etc/postfix/sender_canonical'
```
=> New `canonicals` parameter of `postfix::canonical` types
